data:
  dir: "/data/serrano/"
  dataset_name: navier-stokes-dino
  ntrain : 
  ntest : 
  data_to_encode: 
  sub_from : 4
  sub_tr : 1
  sub_te : 1
  seed: 123
  same_grid: True
  setting : 'all'
  sequence_length_optim : 
  sequence_length_in : 40
  sequence_length_out : 0

optim:
  checkpoint_path: 
  batch_size: 6
  batch_size_val: 
  learning_rate : 1e-5
  epochs : 12000

deeponet:
  model_type : "mlp"
  width: 250
  trunk_depth: 4
  branch_depth: 4
  
wandb:
  entity: "spatiotemp-isir"
  project: "functa2functa"
  name: 
  id: 
  dir: 
  sweep_id: 

jz: 
  program: training/inr.py
  mode: dev
  partition: gpu_p2

