defaults:
  - _self_
  - data: null
  - optim: null
  - inr: null
  - wandb: null

data:
  dir: "/data/serrano/"
  dataset_name: "airfoil-flow" 
  data_to_encode:
  ntrain : 
  ntest : 
  sub_tr : 1
  sub_from : 1
  sub_te : 1
  seed: 123
  same_grid: True
  sequence_length: 20

optim:
  batch_size: 32
  batch_size_val: 
  lr_inr : 5e-6
  gamma_step : 0.9
  lr_code : 0.01
  meta_lr_code : 0
  weight_decay_code: 0
  inner_steps : 3
  test_inner_steps : 3
  epochs : 1000
  lr_mlp : 1e-3
  weight_decay_mlp: 0

inr_in:
  model_type : "siren"
  latent_dim : 256
  depth : 4
  hidden_dim : 256
  w0 : 20
  use_latent: True
  modulate_scale: False
  modulate_shift: True
  hypernet_depth: 1
  hypernet_width: 128
  last_activation: 
  loss_type: "mse"

inr_out:
  model_type : "siren"
  latent_dim : 256
  depth : 4
  hidden_dim : 256
  w0 : 50
  use_latent: True
  modulate_scale: False
  modulate_shift: True
  hypernet_depth: 1
  hypernet_width: 128
  last_activation: 
  loss_type: "mse"

model:
  model_type: resnet
  depth: 3
  width: 128
  dropout: 0
  activation: swish

# airfoil
inr:
  inner_steps: 3
  run_name: 
  run_dict:
    pressure: denim-frost-3448
    density: fluent-planet-3586
    vx: gallant-jazz-3402
    vy: fresh-wave-3583

wandb:
  entity: "spatiotemp-isir"
  project: "functa2functa"
  name: 
  id: 
  dir: 
  sweep_id: 


jz: 
  program: training/inr.py
  mode: dev
  partition: gpu_p2