defaults:
  - _self_
  - data: null
  - optim: null
  - inr: null
  - wandb: null

data:
  dir: "/data/serrano/"
  dataset_name: "shallow-water-dino" 
  data_to_encode:
  ntrain : 
  ntest : 
  sub_from :
  sub_tr : 2
  sub_te : 2
  seed: 123
  same_grid: True
  seq_inter_len : 20 
  seq_extra_len : 20

optim:
  batch_size: 32
  batch_size_val: 
  lr_inr : 0.000005
  gamma_step : 0.9
  lr_code : 0.01
  meta_lr_code : 0.000005
  weight_decay_code: 0
  inner_steps : 3
  test_inner_steps : 3
  epochs : 10000

inr:
  model_type : "mfn"
  latent_dim : 128
  depth : 4
  hidden_dim : 64
<<<<<<< HEAD:template/config/inr/mfn.yaml
  input_scale : 32
=======
  input_scales : 64
>>>>>>> origin:inr/config/mfn.yaml

wandb:
  entity: "spatiotemp-isir"
  project: "functa2functa"
  name: 
  id: 
  dir: 
  saved_checkpoint : False
  sweep_id: 


jz: 
  program: training/inr..py
  mode: dev
  partition: gpu_p2